// SplinterDots Quickshell bar.
// Generated by SplinterDots.

import Quickshell
import Quickshell.Hyprland
import Quickshell.Io
import QtQuick
import QtQuick.Layouts

Variants {
  model: Quickshell.screens

  delegate: Component {
    PanelWindow {
      id: root
      property int activeWorkspace: 1
      property string screenName: modelData.name
      required property var modelData
      screen: modelData

      anchors {
        top: true
        bottom: false
        left: true
        right: true
      }

      margins {
        top: 8
        bottom: 0
        left: 10
        right: 10
      }

      implicitHeight: 34
      color: "transparent"

      Process {
        id: stateProc
        command: ["sh", "-c", "hyprctl monitors -j"]
        running: true
        stdout: StdioCollector {
          onStreamFinished: {
            try {
              var monitors = JSON.parse(this.text)
              for (var i = 0; i < monitors.length; i++) {
                if (monitors[i].name === root.screenName && monitors[i].activeWorkspace) {
                  root.activeWorkspace = monitors[i].activeWorkspace.id
                }
              }
            } catch (e) {
            }
          }
        }
      }

      Timer {
        interval: 120
        running: true
        repeat: true
        onTriggered: { stateProc.running = false; stateProc.running = true }
      }

      Rectangle {
        anchors.fill: parent
        radius: 8
        color: "#ea282828"
        border.width: 1
        border.color: "#3c3836"

        RowLayout {
          anchors.fill: parent
          anchors.leftMargin: 14
          anchors.rightMargin: 14
          spacing: 14

          Row {
            Layout.alignment: Qt.AlignLeft | Qt.AlignVCenter
            spacing: 7

            Rectangle {
              id: easyeffects_left_0
              property bool effectsEnabled: false
              width: 62
              height: 26
              anchors.verticalCenter: parent.verticalCenter
              radius: 6
              color: effectsEnabled ? "#89b4fa" : "#3c3836"
              border.color: effectsEnabled ? "#89b4fa" : "#bdae93"
              border.width: 1

              Text {
                anchors.centerIn: parent
                text: easyeffects_left_0.effectsEnabled ? "󰓃 FX ON" : "󰓃 FX OFF"
                color: "#ebdbb2"
                font.pixelSize: 12
                font.family: "Symbols Nerd Font"
                font.bold: true
              }

              MouseArea {
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: {
                  easyeffectsToggle_left_0.running = false
                  easyeffectsToggle_left_0.running = true
                }
              }

              Process {
                id: easyeffectsStatus_left_0
                command: ["sh", "-c", "pgrep -x easyeffects >/dev/null && printf 1 || printf 0"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: easyeffects_left_0.effectsEnabled = this.text.trim() === "1"
                }
              }

              Process {
                id: easyeffectsToggle_left_0
                command: ["sh", "-c", "if pgrep -x easyeffects >/dev/null; then pkill -x easyeffects; else easyeffects --gapplication-service >/dev/null 2>&1 & fi; sleep 0.4; printf done"]
                stdout: StdioCollector {
                  onStreamFinished: {
                    easyeffectsStatus_left_0.running = false
                    easyeffectsStatus_left_0.running = true
                  }
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: {
                  easyeffectsStatus_left_0.running = false
                  easyeffectsStatus_left_0.running = true
                }
              }
            }


            Text {
              id: txt_left_1
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: statusProc_left_1
                command: ["sh", "-c", "wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null | awk '{v=int($2*100); if($3==\"[MUTED]\") print \"󰝟 muted\"; else print \" \" v \"%\"}'"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_1.text = this.text.split("\\n").join("").trim()
                }
              }

              Process {
                id: clickProc_left_1
                command: ["sh", "-c", "pavucontrol"]
              }

              MouseArea {
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: {
                  clickProc_left_1.running = false
                  clickProc_left_1.running = true
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: {
                  statusProc_left_1.running = false
                  statusProc_left_1.running = true
                }
              }
            }


            Text {
              id: txt_left_2
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_left_2
                command: ["sh", "-c", "printf \"microphone\""]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_2.text = "" + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: { proc_left_2.running = false; proc_left_2.running = true }
              }
            }


            Text {
              id: txt_left_3
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_left_3
                command: ["sh", "-c", "nmcli -t -f DEVICE,STATE device 2>/dev/null | awk -F: '$2==\"connected\"{print \"󰤨 \" $1; exit}'"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_3.text = "" + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: { proc_left_3.running = false; proc_left_3.running = true }
              }
            }


            Text {
              id: txt_left_4
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: statusProc_left_4
                command: ["sh", "-c", "bluetoothctl show 2>/dev/null | grep -q 'Powered: yes' && printf ' on' || printf ' off'"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_4.text = this.text.split("\\n").join("").trim()
                }
              }

              Process {
                id: clickProc_left_4
                command: ["sh", "-c", "overskride"]
              }

              MouseArea {
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: {
                  clickProc_left_4.running = false
                  clickProc_left_4.running = true
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: {
                  statusProc_left_4.running = false
                  statusProc_left_4.running = true
                }
              }
            }


            Text {
              id: txt_left_5
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_left_5
                command: ["sh", "-c", "bat=$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null || cat /sys/class/power_supply/BAT1/capacity 2>/dev/null); [ -n \"$bat\" ] && printf '󰁹 %s%%' \"$bat\""]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_5.text = "" + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: { proc_left_5.running = false; proc_left_5.running = true }
              }
            }


            Text {
              id: txt_left_6
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_left_6
                command: ["sh", "-c", "brightnessctl -m 2>/dev/null | awk -F, '{print \"󰃠 \" $4}'"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_6.text = "" + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: { proc_left_6.running = false; proc_left_6.running = true }
              }
            }


            Text {
              id: txt_left_7
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_left_7
                command: ["sh", "-c", "top -bn1 | awk -F'[, ]+' '/Cpu\\(s\\)/{print \" \" int($2+$4) \"%\"}'"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_7.text = "" + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: { proc_left_7.running = false; proc_left_7.running = true }
              }
            }


            Text {
              id: txt_left_8
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_left_8
                command: ["sh", "-c", "free -m | awk '/^Mem/{printf \" %dMB\", $3}'"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_8.text = "" + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: { proc_left_8.running = false; proc_left_8.running = true }
              }
            }


            Text {
              id: txt_left_9
              anchors.verticalCenter: parent.verticalCenter
              color: "#ebdbb2"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_left_9
                command: ["sh", "-c", "sensors 2>/dev/null | awk '/Package id 0|Tctl|temp1/{gsub(/[+°C]/, \"\", $2); print \" \" int($2) \"°C\"; exit}'"]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_left_9.text = "" + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1500
                running: true
                repeat: true
                onTriggered: { proc_left_9.running = false; proc_left_9.running = true }
              }
            }

          }

          Item { Layout.fillWidth: true }

          Row {
            Layout.alignment: Qt.AlignCenter
            spacing: 7

          }

          Item { Layout.fillWidth: true }

          Row {
            Layout.alignment: Qt.AlignRight | Qt.AlignVCenter
            spacing: 7

          }
        }
      }
    }
  }
}
