// SplinterDots Quickshell bar.
// Generated by SplinterDots.

import Quickshell
import Quickshell.Io
import QtQuick
import QtQuick.Layouts

Variants {
  model: Quickshell.screens

  delegate: Component {
    PanelWindow {
      id: root
      property int activeWorkspace: 1
      property string screenName: modelData.name
      required property var modelData
      screen: modelData

      anchors {
        top: true
        bottom: false
        left: true
        right: true
      }

      margins {
        top: 8
        bottom: 0
        left: 10
        right: 10
      }

      implicitHeight: 40
      color: "transparent"

      Process {
        id: stateProc
        command: ["sh", "-c", "hyprctl monitors -j"]
        running: true
        stdout: StdioCollector {
          onStreamFinished: {
            try {
              var monitors = JSON.parse(this.text)
              for (var i = 0; i < monitors.length; i++) {
                if (monitors[i].name === root.screenName && monitors[i].activeWorkspace) {
                  root.activeWorkspace = monitors[i].activeWorkspace.id
                }
              }
            } catch (e) {
            }
          }
        }
      }

      Timer {
        interval: 40
        running: true
        repeat: true
        onTriggered: { stateProc.running = false; stateProc.running = true }
      }

      Rectangle {
        anchors.fill: parent
        radius: 28
        color: "#ea241b2e"
        border.width: 1
        border.color: "#392a49"

        RowLayout {
          anchors.fill: parent
          anchors.leftMargin: 14
          anchors.rightMargin: 14
          spacing: 14

          Row {
            Layout.alignment: Qt.AlignLeft | Qt.AlignVCenter
            spacing: 7

            Row {
              id: workspaces_left_0
              anchors.verticalCenter: parent.verticalCenter
              spacing: 5

              Repeater {
                model: 5

                delegate: Rectangle {
                  width: 32
                  height: 32
                  radius: 24
                  color: "#392a49"
                  border.color: "#ddb0cd"
                  border.width: 1

                  Text {
                    anchors.centerIn: parent
                    text: modelData + 1
                    color: "#ffebf6"
                    font.pixelSize: 12
                    font.family: "Symbols Nerd Font"
                  }

                  MouseArea {
                    anchors.fill: parent
                    cursorShape: Qt.PointingHandCursor
                    onClicked: {
                      Hyprland.dispatch("workspace " + (modelData + 1))
                    }
                  }
                }
              }
            }

          }

          Item { Layout.fillWidth: true }

          Row {
            Layout.alignment: Qt.AlignCenter
            spacing: 7

            Text {
              id: txt_center_0
              anchors.verticalCenter: parent.verticalCenter
              color: "#ffebf6"
              font.pixelSize: 12
              font.family: "Symbols Nerd Font"
              text: ""

              Process {
                id: proc_center_0
                command: ["sh", "-c", "date +\"%a %d %b  %H:%M\""]
                running: true
                stdout: StdioCollector {
                  onStreamFinished: txt_center_0.text = " " + this.text.split("\\n").join("").trim()
                }
              }

              Timer {
                interval: 1000
                running: true
                repeat: true
                onTriggered: { proc_center_0.running = false; proc_center_0.running = true }
              }
            }

          }

          Item { Layout.fillWidth: true }

          Row {
            Layout.alignment: Qt.AlignRight | Qt.AlignVCenter
            spacing: 7

            Item {
              id: media_right_0
              width: 32
              height: 40

              Process {
                id: proc_right_0_menu_proc
                command: ["sh", "-c", "splinter-media-menu"]
              }

              Rectangle {
                id: mediaButton
                anchors.centerIn: parent
                width: 32
                height: 32
                radius: 24
                color: "#392a49"
                border.color: "#89b4fa"
                border.width: 1

                Text {
                  anchors.centerIn: parent
                  text: ""
                  color: "#ffebf6"
                  font.family: "Symbols Nerd Font"
                  font.pixelSize: 12
                }

                MouseArea {
                  anchors.fill: parent
                  cursorShape: Qt.PointingHandCursor
                  acceptedButtons: Qt.LeftButton
                  onClicked: {
                    proc_right_0_menu_proc.running = false
                    proc_right_0_menu_proc.running = true
                  }
                }
              }
            }

          }
        }
      }
    }
  }
}
