foreground #f4f4f5
background #111111
selection_foreground #111111
selection_background #d4d4d8
cursor #f4f4f5
cursor_text_color #111111

color0 #18181b
color1 #a1a1aa
color2 #d4d4d8
color3 #e4e4e7
color4 #fafafa
color5 #c7c7cc
color6 #e5e5e5
color7 #f4f4f5
color8 #52525b
color9 #a1a1aa
color10 #d4d4d8
color11 #e4e4e7
color12 #fafafa
color13 #c7c7cc
color14 #e5e5e5
color15 #ffffff
