foreground #ecfeff
background #050816
selection_foreground #050816
selection_background #00e5ff
cursor #00e5ff
cursor_text_color #050816

color0 #111827
color1 #ff2a6d
color2 #05ffa1
color3 #f9f871
color4 #00e5ff
color5 #bd00ff
color6 #01cdfe
color7 #d1f7ff
color8 #374151
color9 #ff4f8b
color10 #44ffbd
color11 #fbff91
color12 #4df1ff
color13 #cf5cff
color14 #5ee7ff
color15 #ffffff
