#!/usr/bin/env bash

info="$(hyprctl activewindow -j 2>/dev/null)"

title="$(printf '%s' "$info" | jq -r '.title // ""')"
class="$(printf '%s' "$info" | jq -r '.class // ""')"

case "$title:$class" in
  *"Splinter Media Controls"*|*splinter-media-menu*)
    exit 0
    ;;
esac

hyprctl dispatch fullscreen 1
